# Built with Jekyll 3.2.0

# Setup
title:               Introduction to Text Analysis
tagline:             'A Coursebook'
description:         'Ed is a Jekyll theme designed for textual editors based on minimal computing principles, and focused on legibility and flexibility.'
url:                 'http://bmw9t.github.io'
baseurl:             'textanalysiscoursebook'

# About/contact
author:
  name:              Brandon Walsh
  url:               https://bmw9t.github.io/textanalysiscoursebook/
  email:             walsh.brandon.michael@gmail.com

# Permalinks

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Custom vars
version:             0.0.6

# Exclusions from the final site
exclude: [optional, vendor]


